title: ng config
url: command-ng-config
entries:
  - type: text
    text: >-
      ```

      ng config [key] [value]

      ```


      Get/set configuration values. `[key]` should be in JSON path format. Example: `a[3].foo.bar[2]`. 


      If only the `[key]` is provided it will get the value. If both the `[key]` and `[value]` are provided it will set the value.



      ## Options
  - type: command-param
    head: global
    description: "Get/set the value in the global configuration (in your home directory). "
    name: global
    headId: global
    aliases: g
    paramType: boolean
